// prerender.js
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import React from 'react'; // Import React for JSX transform/createElement

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function prerender() {
  const distPath = path.resolve(__dirname, 'dist');
  const indexPath = path.resolve(distPath, 'index.html');
  const tempSsrAppPath = path.resolve(__dirname, './temp-ssr-app.js');
  const tempSsrCssPath = path.resolve(__dirname, './temp-ssr-app.css');

  let html = await fs.readFile(indexPath, 'utf-8');

  const esbuild = await import('esbuild');

  try {
    // Build the React App for Node.js environment
    const serverBuildResult = await esbuild.build({
      entryPoints: [path.resolve(__dirname, 'src/App.tsx')],
      bundle: true,
      platform: 'node',
      format: 'esm',
      outfile: tempSsrAppPath,
      external: ['react-dom/server', 'react-dom'],
      jsx: 'transform',
      define: {
        'process.env.NODE_ENV': JSON.stringify('production'),
        'global': 'globalThis'
      },
      resolveExtensions: ['.tsx', '.ts', '.jsx', '.js', '.json'],
      logLevel: 'info',
      target: 'es2020',
    });

    if (serverBuildResult.errors.length > 0) {
      throw new Error(`esbuild failed: ${JSON.stringify(serverBuildResult.errors)}`);
    }

    // Dynamically import the server-rendered component
    const { default: App } = await import(`${tempSsrAppPath}?t=${Date.now()}`);
    const ReactDOMServer = await import('react-dom/server');

    // Render the App to a string
    const appHtml = ReactDOMServer.renderToString(React.createElement(App));

    // Inject the rendered app HTML into the index.html
    html = html.replace('<div id="root"></div>', `<div id="root">${appHtml}</div>`);

    // Optional: Inline the CSS generated by esbuild to prevent FOUC
    try {
      const css = await fs.readFile(tempSsrCssPath, 'utf-8');
      html = html.replace('</head>', `<style>${css}</style></head>`);
      console.log('Inlined critical CSS into index.html');
    } catch (e) {
      // CSS file might not exist if there are no styles
      console.log('No temporary CSS file found to inline.');
    }

    // Write the modified HTML back
    await fs.writeFile(indexPath, html);
    console.log('Prerendering complete!');
  } catch (error) {
    console.error('Prerendering failed:', error);
    process.exit(1);
  } finally {
    // Clean up temporary files
    await Promise.allSettled([
      fs.unlink(tempSsrAppPath),
      fs.unlink(tempSsrCssPath)
    ]);
  }
}

prerender().catch(console.error);