export const introText = {
  title: "The New and Improved 1988 Rice Trasher Purity Test",
  description: "There's no doubt in anyone's mind that the old Purity Test, first printed in this very paper, is an enduring classic which should still be mandatory for all entering freshmen. However, it has been noted that the test is perhaps a little outdated. With this in mind, we at the backpage are proud to offer the new, improved, 1988 Purity Test.",
  instructions: "For each of the following things you have done, give yourself one point. When you're done, subtract the total from 150. This is your score. Original source: <a href=\"/rice-test\" class=\"internal-link\">The Rice Thresher (April 1, 1988)</a>",
  definitions: [
    { term: "Sexual activity", definition: "Either sexual intercourse or heavy activity with both (or all) parties naked and with orgasm as the ultimate goal. This is in response to complaints that intercourse is not always the most reliable indicator of purity." }
  ]
};

export interface Question {
  text: string;
  emoji: string;
}

export interface Section {
  title?: string;
  questions: Question[];
}

export interface ScoringCategory {
  min: number;
  max: number;
  title: string;
  text: string;
}

export const sections: Section[] = [
  {
    title: "General",
    questions: [
      { text: "Kissed a member of the opposite sex", emoji: "💋" },
      { text: "French kissed a member of the opposite sex", emoji: "👅" },
      { text: "Made out with a member of the opposite sex", emoji: "💑" },
      { text: "Scrogged (naked making out) with a member of the opposite sex", emoji: "🔥" },
      { text: "Cunnilingus with a member of the opposite sex", emoji: "🍭" },
      { text: "Fellatio with a member of the opposite sex", emoji: "🍦" },
      { text: "69 with a member of the opposite sex", emoji: "♋" },
      { text: "Anal intercourse with a member of the opposite sex", emoji: "🍑" },
      { text: "Felching (oral act after anal sex) with a member of the opposite sex", emoji: "🧼" },
      { text: "Sexual intercourse with a member of the opposite sex", emoji: "🏩" },
      { text: "Golden Showers (urination on partner)", emoji: "🚿" },
      { text: "Kissed a member of the same sex", emoji: "🌈" },
      { text: "French kissed a member of the same sex", emoji: "🏳️‍🌈" },
      { text: "Made out with a member of the same sex", emoji: "👬" },
      { text: "Scrogged (naked making out) with a member of the same sex", emoji: "✨" },
      { text: "Cunnilingus with a member of the same sex", emoji: "💎" },
      { text: "Fellatio with a member of the same sex", emoji: "🍌" },
      { text: "69 with a member of the same sex", emoji: "🔄" },
      { text: "Anal intercourse with a member of the same sex", emoji: "💫" },
      { text: "Felching (oral act after anal sex) with a member of the same sex", emoji: "🌀" },
    ]
  },
  {
    title: "Sexual Activity with:",
    questions: [
      { text: "An animal", emoji: "🐾" },
      { text: "An inanimate object", emoji: "🧸" },
      { text: "A relative", emoji: "🌳" },
      { text: "Someone asleep or passed out", emoji: "💤" },
      { text: "Someone tripping (on drugs)", emoji: "🍄" },
      { text: "Roommate's boyfriend or girlfriend", emoji: "🏠" },
      { text: "Two people (menage a trois)", emoji: "🥉" },
      { text: "More than two people (orgy)", emoji: "🎭" },
      { text: "Your advisor/freshman", emoji: "🎓" },
      { text: "A campus police officer", emoji: "👮" },
      { text: "Someone married/engaged (not to you)", emoji: "💍" },
      { text: "Someone over 30", emoji: "👴" },
      { text: "An ex", emoji: "🔙" },
      { text: "A faculty member", emoji: "📖" },
      { text: "A prostitute", emoji: "💸" },
      { text: "A stranger", emoji: "👤" },
      { text: "A non-Rice stranger", emoji: "🦉" },
      { text: "Someone whose name you couldn't remember afterwards", emoji: "❓" },
    ]
  },
  {
    title: "Sexual activity:",
    questions: [
      { text: "Without birth control", emoji: "🎲" },
      { text: "While passed out or asleep", emoji: "🛌" },
      { text: "While tied up", emoji: "⛓️" },
      { text: "Using food", emoji: "🍓" },
      { text: "With whips, chains, or other S & M type gadgets", emoji: "🖤" },
      { text: "Any other bizarre sexual toy", emoji: "🔋" },
      { text: "Standing up", emoji: "🧍" },
      { text: "Doggie style", emoji: "🐕" },
      { text: "Any other position besides woman on top or missionary", emoji: "🤸" },
      { text: "In a hot tub", emoji: "♨️" },
      { text: "Underwater", emoji: "🌊" },
      { text: "With three different people in one weekend", emoji: "📅" },
      { text: "With two different people in one night", emoji: "🌙" },
      { text: "With more than three different people in one weekend", emoji: "🗓️" },
      { text: "Within the last week", emoji: "⏳" },
      { text: "Within the last day", emoji: "☀️" },
      { text: "Within the last hour", emoji: "⌚" },
      { text: "More than once a day (average)", emoji: "🔁" },
      { text: "Lost virginity before this year", emoji: "🗝️" },
      { text: "Lost virginity before college (Rice)", emoji: "🏫" },
      { text: "Lost virginity before high school", emoji: "🎒" },
      { text: "Sexual activity while another person is in the room", emoji: "👀" },
      { text: "In a classroom", emoji: "📝" },
      { text: "In a commons, private dining room (PDR), or college library", emoji: "🍴" },
      { text: "In the library (Fondren), any classroom building, Lovett Hall, or Ryon lab (during operating hours)", emoji: "📚" },
      { text: "In the stadium", emoji: "🏟️" },
      { text: "At the computer lab (Mudd)",
        emoji: "💻" },
      { text: "On a roof or sundeck", emoji: "🌇" },
      { text: "Willy's statue (campus landmark)", emoji: "🗿" },
      { text: "At the beach", emoji: "🏖️" },
      { text: "In the steam tunnels", emoji: "🚇" },
      { text: "Gotten caught or caught someone", emoji: "🚨" },
      { text: "Seen a porno flick", emoji: "🎥" },
      { text: "Read Playboy, Playgirl, Penthouse, Forum or Hustler", emoji: "📰" },
      { text: "Seen a stripper/nude dancer", emoji: "💃" },
      { text: "Ordered anything that came in a plain brown wrapper (discreet packaging)", emoji: "📦" },
      { text: "Been flashed", emoji: "🧥" },
      { text: "Flashed someone", emoji: "⚡" },
      { text: "Sunbathed nude", emoji: "🌞" },
      { text: "Committed voyeurism", emoji: "🔭" },
      { text: "Spent the night with a member of the opposite sex", emoji: "🌃" },
      { text: "Cohabitated with a member of the opposite sex (nonsexual basis)", emoji: "🛋️" },
      { text: "Cohabitated with a member of the opposite sex (sexual basis)", emoji: "🏠" },
      { text: "Never been to church", emoji: "⛪" },
      { text: "Have not attended church since coming to college (Rice)", emoji: "📉" },
      { text: "Ditched a date", emoji: "🏃" },
      { text: "Masturbated", emoji: "✊" },
      { text: "Masturbated with another person present", emoji: "🤝" },
      { text: "Masturbated using sexual aids", emoji: "🛠️" },
      { text: "Had a Venereal Disease (STI)", emoji: "🏥" },
      { text: "Vandalised/stolen anything from another college", emoji: "🧨" },
      { text: "Had an abortion", emoji: "🏥" },
      { text: "Used colored or ribbed condoms", emoji: "🎈" },
      { text: "Used joy jelly (lubricant), flavored underpants, etc.", emoji: "🍯" },
      { text: "Shoplifted", emoji: "🛍️" },
      { text: "Been arrested", emoji: "🚔" },
      { text: "Stolen a sign", emoji: "🛑" },
      { text: "Committed a misdemeanor (other than sign stealing)", emoji: "📜" },
      { text: "Cheated or violated the honor code", emoji: "📉" },
      { text: "Witnessed a crime", emoji: "🕵️" },
      { text: "Committed assault", emoji: "👊" },
      { text: "Been convicted of anything", emoji: "⚖️" },
      { text: "Run with Baker 13 (undie run tradition)", emoji: "🏃‍♂️" },
      { text: "Thrown anything off of Lovett or Sid (dormitory towers)", emoji: "☄️" },
      { text: "Driven drunk", emoji: "🚗" },
      { text: "Been caught driving drunk", emoji: "🛑" },
      { text: "Used fake ID", emoji: "🆔" },
      { text: "Own fake ID", emoji: "💳" },
      { text: "Gotten a parking ticket (Rice)", emoji: "🎫" },
      { text: "Gotten a real ticket", emoji: "🚔" },
      { text: "Lied on a job application", emoji: "🤥" },
      { text: "Owned a deadly weapon (not Mace)", emoji: "🗡️" },
      { text: "Assaulted a police officer or campus police", emoji: "🥊" },
      { text: "Committed statutory rape", emoji: "⚖️" },
      { text: "Committed non-statutory rape", emoji: "🚨" },
      { text: "Gone steam tunneling (exploring underground tunnels)", emoji: "🔦" },
      { text: "Gone swimming in Rupp's pool (campus pool)", emoji: "🏊" },
      { text: "Snuck into party or movie", emoji: "🎟️" },
      { text: "Own Ozzy Osbourne album/tape/CD", emoji: "🎸" },
      { text: "Been to House of Guys (specific party spot)", emoji: "🏠" },
      { text: "Been picked up at House of Guys", emoji: "🙋" },
      { text: "Responded to/placed a personal ad (not in the school paper)", emoji: "🗞️" },
      { text: "Cruised Westheimer (a major street)", emoji: "🏎️" },
      { text: "Gone to a singles bar", emoji: "🍸" },
      { text: "Gotten picked up", emoji: "🤝" },
      { text: "Drunk alcohol", emoji: "🍺" },
      { text: "Been drunk", emoji: "🥴" },
      { text: "Get drunk at least once a week", emoji: "🍻" },
      { text: "Vomited (Booted)", emoji: "🤮" },
      { text: "Passed out", emoji: "😵" },
      { text: "Vomited/passed out at College Night", emoji: "🎊" },
      { text: "Vomited/passed out on date", emoji: "🥀" },
      { text: "Joined Rally Club", emoji: "📣" },
      { text: "Vomited on faculty member/parent/Rupp", emoji: "😱" },
      { text: "Used alcohol to lower inhibitions (skank)", emoji: "🥂" },
      { text: "Vomited/passed out at Esperanza/Rondelet/Archi-Arts (dances)", emoji: "💃" },
      { text: "Vomited/passed out before noon", emoji: "🌅" },
      { text: "Participated in Lovett Beerathon (or been drunk 24 hours independently)", emoji: "🏆" },
      { text: "Gone to NOD (Night of Decadence party)", emoji: "👹" },
      { text: "Smoked", emoji: "🚬" },
      { text: "Habitually smoke", emoji: "💨" },
      { text: "Used Ecstasy (X)", emoji: "💊" },
      { text: "Smoked pot", emoji: "🌿" },
      { text: "Used cocaine", emoji: "❄️" },
      { text: "Used crack", emoji: "⚡" },
      { text: "Abused prescription drugs", emoji: "💊" },
      { text: "Mixed drugs & alcohol", emoji: "🧪" },
      { text: "Used drugs before college (Rice)", emoji: "🧪" },
      { text: "Sold drugs", emoji: "💰" },
      { text: "Been arrested in connection with drugs", emoji: "🚔" },
      { text: "Done shrooms", emoji: "🍄" },
      { text: "Been to Counterball (annual event)", emoji: "🏀" }
    ]
  }
];

export const scoringCategories: ScoringCategory[] = [
  { min: 145, max: 150, title: "Angelic", text: "Wynn I-have-been-at-Rice-for-almost-a-year-and-I-still-don't-know-what-felching-is-so-I-asked-my-mom Martin." },
  { min: 130, max: 144, title: "Saint", text: "Wynn I-have-been-at-Rice-for-almost-a-year-and-I-still-don't-know-what-felching-is-so-I-asked-my-mom Martin." },
  { min: 110, max: 129, title: "Pure", text: "Jenny I-am-a-hot-sexy-and-voluptuous-babe-in-the-wild-and-wet-fantasy-of-every-Sid-Rich-geek Berry" },
  { min: 95, max: 109, title: "Innocent", text: "Jenny I-am-a-hot-sexy-and-voluptuous-babe-in-the-wild-and-wet-fantasy-of-every-Sid-Rich-geek Berry" },
  { min: 80, max: 94, title: "Curious", text: "Paul Sat-by-his-phone-for-hours-and-still-didn't-get-invited-to-Randomlay Angles" },
  { min: 65, max: 79, title: "Experienced", text: "Paul Sat-by-his-phone-for-hours-and-still-didn't-get-invited-to-Randomlay Angles" },
  { min: 50, max: 64, title: "Adventurous", text: "Mike Yes-I-know-I-look-like-Paul-but-there's-no-way-I-would-use-his-ID Raphael" },
  { min: 35, max: 49, title: "Wild", text: "Mike Yes-I-know-I-look-like-Paul-but-there's-no-way-I-would-use-his-ID Raphael" },
  { min: 20, max: 34, title: "Party Animal", text: "Michèle Whip-Me-Beat-Me-but-don't-lay-a-hand-on-my-dog Wucker." },
  { min: 10, max: 19, title: "Fallen Angel", text: "Michèle Whip-Me-Beat-Me-but-don't-lay-a-hand-on-my-dog Wucker." },
  { min: 0, max: 9, title: "Legend", text: "Michèle Whip-Me-Beat-Me-but-don't-lay-a-hand-on-my-dog Wucker." },
];
